
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: nilsweber/block:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7

    # # Steps represent a sequence of tasks that will be executed as part of the job
    # steps:
    #   # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    #   - uses: actions/checkout@v2
    #     name: Check out code

    #   - uses: mr-smithers-excellent/docker-build-push@v5
    #     name: Build & push Docker image
    #     with:
    #       image: hajen/blockablock
    #       tags: v1, latest
    #       registry: docker.io
    #       dockerfile: Dockerfile
    #       username: ${{ secrets.DOCKER_USERNAME }}
    #       password: ${{ secrets.DOCKER_PWORD }}